version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/home/app/config
      - ./custom-addons:/home/app/addons
    stdin_open: true
    command: odoo -c /home/app/config/odoo_develop.conf
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: